# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='discrption',
            field=models.TextField(blank=True),
        ),
    ]
